services:
  myapp:
    image: sdw:latest
    ports:
      - "80:80"
    environment:
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
    volumes:
      - sdw_data:/mount
volumes:
  sdw_data: