services:
  myapp:
    image: data4knowledge/sdw:latest
    ports:
      - "8000:8000"
    environment:
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      ROOT_URL: ${ROOT_URL}
      SINGLE_USER: ${SINGLE_USER}
    volumes:
      - sdw_data:/mount
volumes:
  sdw_data: